apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cicd-vijd
    app.kubernetes.io/instance: cicd-vijd-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: cicd-vijd
spec:
  selector:
    app: cicd-vijd
  type: NodePort
  ports:
    - protocol: TCP
    port: 80
    targetPort: 80
